/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetChatMessagesResponse { 
    DateSend?: string | null;
    ChatMessage?: string | null;
    IdUser?: number | null;
    Login?: string | null;
    Firstname?: string | null;
    Surname?: string | null;
    Avatar?: string | null;
}

