/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetMessageRequest } from './get-message-request';


export interface GetUpdateMeetingRequest { 
    DateMeeting?: string | null;
    Place?: string | null;
    Quantity?: number | null;
    Description?: string | null;
    IsIndependent?: boolean | null;
    Column?: Array<string> | null;
    Message?: GetMessageRequest;
}

