/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetMessagesUsersMeetingsResponse { 
    Answer?: string | null;
    DateAdd?: string | null;
    DateMeeting?: string | null;
    Place?: string | null;
    Quantity?: number | null;
    Description?: string | null;
    Email?: string | null;
    Login?: string | null;
    Firstname?: string | null;
    Surname?: string | null;
    PhoneNumber?: number | null;
    IsAdmin?: boolean | null;
    IdUser?: number | null;
    IdMeeting?: number | null;
    WaitingTime?: string | null;
    Avatar?: string | null;
    IdMessage?: number | null;
    IdAuthor?: number | null;
    IdGroup?: number | null;
    IdTeam?: number | null;
    IdGuest?: number | null;
    IsIndependent?: boolean | null;
    WaitingTimeDecision?: number | null;
    TeamColor?: string | null;
}

