/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetMeetingRequest } from './get-meeting-request';
import { GetTeamRequest } from './get-team-request';
import { GetMessageRequest } from './get-message-request';


export interface GetUsersMeetingsRequest { 
    Meeting?: GetMeetingRequest;
    Message?: GetMessageRequest;
    Team?: Array<GetTeamRequest> | null;
}

