/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetMeetingUsersGroupsResponse { 
    Name?: string | null;
    Login?: string | null;
    Firstname?: string | null;
    Surname?: string | null;
    AccountType?: string | null;
    Email?: string | null;
    PhoneNumber?: number | null;
    DateMeeting?: string | null;
    Place?: string | null;
    Description?: string | null;
    Quantity?: number | null;
    IsAdmin?: boolean | null;
}

