/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetGroupRequest } from './get-group-request';
import { USERS } from './users';


export interface GetCreateGroupRequest { 
    GroupRequest?: GetGroupRequest;
    User?: USERS;
}

