/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GROUPINVITE { 
    ID_GROUP_INVITE?: number | null;
    IDGROUP?: number;
    IDUSER?: number | null;
    EMAIL?: string | null;
    IDAUTHOR?: number;
    DATE_ADD?: string | null;
}

