/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MEETINGS { 
    ID_MEETING?: number | null;
    DATE_MEETING?: string | null;
    PLACE?: string | null;
    QUANTITY?: number | null;
    DESCRIPTION?: string | null;
    IDGROUP?: number | null;
}

