/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MESSAGES { 
    ID_MESSAGE?: number | null;
    IDMEETING?: number | null;
    IDUSER?: number | null;
    ANSWER?: string | null;
    DATE_ADD?: string | null;
    WAITING_TIME?: string | null;
    DATE_RESPONSE?: string | null;
}

