/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NOTIFICATION { 
    ID_NOTIFICATION?: number;
    IDUSER?: number;
    MEETING_NOTIFICATION?: boolean;
    GROUP_INV_NOTIFICATION?: boolean;
    MEETING_ORGANIZER_NOTIFICATION?: boolean;
    TEAM_NOTIFICATION?: boolean;
    UPDATE_MEETING_NOTIFICATION?: boolean;
    TEAM_ORGANIZER_NOTIFICATION?: boolean;
    GROUP_ADD_NOTIFICATION?: boolean;
    MEETING_CANCEL_NOTIFICATION?: boolean;
}

