/**
 * api.pilkarzyk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface USERS { 
    ID_USER?: number;
    LOGIN?: string | null;
    USER_PASSWORD?: string | null;
    EMAIL?: string | null;
    FIRSTNAME?: string | null;
    SURNAME?: string | null;
    PHONE_NUMBER?: number;
    IS_ADMIN?: boolean;
    SALT?: string | null;
    AVATAR?: string | null;
    GROUP_COUNTER?: number;
    SEND_INVITE?: boolean;
}

